name: ACCELQ Github Action CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ACCELQ Github-A Connect
      # You may pin to the exact commit or the version.
      # uses: accelq/accelq-ci-github-actions@953369c4991322d0eb25d68f449a7d8c574c58d1
      uses: accelq/accelq-ci-github-actions@v1.1
      with:
        # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
        appURL: "https://training.accelq.io/"
        # Your ACCELQ User ID
        userName: "nisha.rajput@dazeworks.com"
        # API key available in Profile section of ACCELQ
        apiKey: "-YYe5-mXyXnKHHdIOi6Kcn4OhptH0Zymhn1IRepW0fs"
        # Tenant Code displayed in the Profile section of ACCELQ
        tenantCode: "accelqtraining"
        # This ID should come from the CI job you saved in ACCELQ application
        jobId: "22880"
